spring:
  application:
    name: backend-service
  datasource:
    url: jdbc:mysql://localhost:33006/local-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none

logging:
  pattern:
    level:
      org:
        hibernate:
          orm:
            jdbc:
              bind: trace
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret-key: local-secret-key-local-secret-key-local-secret-key-local-secret-key-local-secret-key

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka