spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none


logging:
  pattern:
    level:
      org:
        hibernate:
          orm:
            jdbc:
              bind: trace
  level:
    org:
      hibernate:
        SQL: debug
        type: trace