spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true


logging:
  pattern:
    level:
      org:
        hibernate:
          orm:
            jdbc:
              bind: trace
  level:
    org:
      hibernate:
        SQL: debug
        type: trace