version: "3.7"

services:
  local-mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: local-mysql
    environment:
      - MYSQL_DATABASE=local-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root@%
      - MYSQL_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/ddl:/docker-entrypoint-initdb.d
    ports:
      - "33006:3306"